export const ActionTypes = {
    // PRODUCT ACTIONS
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS:  "SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    BUY_NOW_PRODUCT: "BUY_NOW_PRODUCT",
    REMOVE_BUY_NOW_PRODUCT: "REMOVE_BUY_NOW_PRODUCT",

    // USER ACTIONS
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    ADD_USER_ADDRESS: "ADD_USER_ADDRESS",
    UPDATE_USER_ADDRESS: "UPDATE_USER_ADDRESS",
    REMOVE_USER_ADDRESS: "REMOVE_USER_ADDRESS",

    // CART ACTIONS
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    EMPTY_CART: "EMPTY_CART",
    INCREASE_CART_COUNT: "INCREASE_CART_COUNT",
    DECREASE_CART_COUNT: "DECREASE_CART_COUNT",
    SYNC_CART: "SYNC_CART"
};